services:
  ros2:
    privileged: true
    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: ros2-jazzy

    stdin_open: true
    tty: true

    network_mode: host

    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: /tmp/.mutter-Xwaylandauth
      QT_X11_NO_MITSHM: "1"
      ROS_DOMAIN_ID: 10

    volumes:
      - ./ros2-ws:/ros2-ws # needed to save workspace changes on host and persist
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # needed to run GUI apps in the container
      - ${XAUTHORITY}:/tmp/.mutter-Xwaylandauth:ro # needed to support Xwayland
      - /dev:/dev # needed to access serial devices in the container
      - /sys:/sys:ro # needed to access kernel and hardware info as read-only
      - /run/udev:/run/udev:ro # needed to access udev rules in the container

    working_dir: /ros2-ws